'use client';

import { useState } from 'react';

interface PacketData {
  appName: string;
  bundleId: string;
  version: string;
  demoEmail: string;
  demoPassword: string;
  testingSteps: string;
  specialInstructions: string;
  hasIAP: boolean;
  iapInstructions: string;
  hasSubscription: boolean;
  subInstructions: string;
  requiresHardware: boolean;
  hardwareNotes: string;
  requiresLocation: boolean;
  locationNotes: string;
}

const INITIAL: PacketData = {
  appName: '',
  bundleId: '',
  version: '',
  demoEmail: '',
  demoPassword: '',
  testingSteps: '',
  specialInstructions: '',
  hasIAP: false,
  iapInstructions: '',
  hasSubscription: false,
  subInstructions: '',
  requiresHardware: false,
  hardwareNotes: '',
  requiresLocation: false,
  locationNotes: '',
};

function generatePacketText(data: PacketData): string {
  const lines: string[] = [];

  lines.push('═══════════════════════════════════════');
  lines.push(`  APP STORE REVIEW PACKET`);
  lines.push(`  ${data.appName || 'Your App'} v${data.version || '1.0'}`);
  lines.push('═══════════════════════════════════════');
  lines.push('');

  if (data.bundleId) {
    lines.push(`Bundle ID: ${data.bundleId}`);
    lines.push('');
  }

  // Demo credentials
  lines.push('── DEMO ACCOUNT ──────────────────────');
  if (data.demoEmail && data.demoPassword) {
    lines.push(`Email:    ${data.demoEmail}`);
    lines.push(`Password: ${data.demoPassword}`);
  } else {
    lines.push('No login required for this app.');
  }
  lines.push('');

  // Testing steps
  lines.push('── TESTING STEPS ─────────────────────');
  if (data.testingSteps.trim()) {
    data.testingSteps.split('\n').forEach((step, i) => {
      const text = step.trim();
      if (text) lines.push(`${i + 1}. ${text}`);
    });
  } else {
    lines.push('1. Launch the app');
    lines.push('2. Log in with demo credentials above');
    lines.push('3. Navigate through all main features');
  }
  lines.push('');

  // IAP
  if (data.hasIAP) {
    lines.push('── IN-APP PURCHASES ──────────────────');
    lines.push(data.iapInstructions.trim() || 'In-app purchases are available. Please use the sandbox environment for testing.');
    lines.push('');
  }

  // Subscriptions
  if (data.hasSubscription) {
    lines.push('── SUBSCRIPTIONS ─────────────────────');
    lines.push(data.subInstructions.trim() || 'Subscription features can be tested in sandbox mode. Auto-renewal periods are shortened for testing.');
    lines.push('');
  }

  // Hardware
  if (data.requiresHardware) {
    lines.push('── HARDWARE REQUIREMENTS ─────────────');
    lines.push(data.hardwareNotes.trim() || 'This app requires specific hardware features. Please see notes below.');
    lines.push('');
  }

  // Location
  if (data.requiresLocation) {
    lines.push('── LOCATION REQUIREMENTS ─────────────');
    lines.push(data.locationNotes.trim() || 'This app uses location services. For testing, any location in the United States will work.');
    lines.push('');
  }

  // Special instructions
  if (data.specialInstructions.trim()) {
    lines.push('── ADDITIONAL NOTES ──────────────────');
    lines.push(data.specialInstructions.trim());
    lines.push('');
  }

  lines.push('═══════════════════════════════════════');
  lines.push(`Generated by Luminetic · ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}`);

  return lines.join('\n');
}

/* ── Shared inline style objects ── */

const sectionLabel: React.CSSProperties = {
  fontFamily: 'var(--mono)',
  fontSize: '0.5rem',
  letterSpacing: 3,
  textTransform: 'uppercase',
  color: 'var(--orange)',
  marginBottom: 20,
};

const inputStyle: React.CSSProperties = {
  width: '100%',
  background: 'rgba(255,255,255,0.03)',
  border: '1px solid var(--border)',
  borderRadius: 0,
  padding: '14px 18px',
  color: 'var(--white)',
  fontFamily: 'var(--mono)',
  fontSize: '0.78rem',
  outline: 'none',
};

const fieldLabel: React.CSSProperties = {
  fontFamily: 'var(--mono)',
  fontSize: '0.5rem',
  letterSpacing: 3,
  textTransform: 'uppercase',
  color: 'var(--text-dim)',
  marginBottom: 8,
  display: 'block',
};

const cardStyle: React.CSSProperties = {
  border: '1px solid var(--border)',
  padding: '28px 32px',
};

/* ── Sub-components ── */

function InputField({ label, value, onChange, placeholder, type = 'text' }: {
  label: string; value: string; onChange: (v: string) => void; placeholder?: string; type?: string;
}) {
  return (
    <div>
      <label style={fieldLabel}>{label}</label>
      <input
        type={type}
        value={value}
        onChange={(e) => onChange(e.target.value)}
        placeholder={placeholder}
        style={inputStyle}
      />
    </div>
  );
}

function TextAreaField({ label, value, onChange, placeholder, rows = 4 }: {
  label: string; value: string; onChange: (v: string) => void; placeholder?: string; rows?: number;
}) {
  return (
    <div>
      <label style={fieldLabel}>{label}</label>
      <textarea
        value={value}
        onChange={(e) => onChange(e.target.value)}
        placeholder={placeholder}
        rows={rows}
        style={{ ...inputStyle, resize: 'none', lineHeight: 1.7 }}
      />
    </div>
  );
}

function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (v: boolean) => void }) {
  return (
    <label
      style={{ display: 'flex', alignItems: 'center', gap: 12, cursor: 'pointer', padding: '6px 0' }}
      onClick={() => onChange(!checked)}
    >
      {/* Sharp rectangular toggle track */}
      <div
        style={{
          width: 36,
          height: 18,
          background: checked ? 'var(--orange)' : 'var(--border)',
          position: 'relative',
          flexShrink: 0,
          transition: 'background 0.15s',
        }}
      >
        {/* Sharp rectangular toggle thumb */}
        <div
          style={{
            width: 12,
            height: 12,
            background: 'var(--white)',
            position: 'absolute',
            top: 3,
            left: checked ? 20 : 4,
            transition: 'left 0.15s',
          }}
        />
      </div>
      <span
        style={{
          fontFamily: 'var(--body)',
          fontSize: '0.82rem',
          color: checked ? 'var(--white)' : 'var(--text-dim)',
        }}
      >
        {label}
      </span>
    </label>
  );
}

/* ── Page ── */

export default function ReviewPacketPage() {
  const [data, setData] = useState<PacketData>(INITIAL);
  const [generated, setGenerated] = useState(false);
  const [packetText, setPacketText] = useState('');
  const [copied, setCopied] = useState(false);

  function update<K extends keyof PacketData>(key: K, value: PacketData[K]) {
    setData((prev) => ({ ...prev, [key]: value }));
  }

  function handleGenerate() {
    const text = generatePacketText(data);
    setPacketText(text);
    setGenerated(true);
  }

  function handleCopy() {
    navigator.clipboard.writeText(packetText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  return (
    <div style={{ maxWidth: 1200, margin: '0 auto', padding: '0 48px 80px' }}>
      {/* ── Hero header ── */}
      <div style={{ paddingTop: 120, marginBottom: 56 }}>
        <div
          style={{
            fontFamily: 'var(--mono)',
            fontSize: '0.5rem',
            letterSpacing: 3,
            textTransform: 'uppercase',
            color: 'var(--orange)',
            marginBottom: 10,
          }}
        >
          // review packet
        </div>
        <h1
          style={{
            fontFamily: 'var(--display)',
            fontSize: 'clamp(3rem, 6vw, 5rem)',
            color: 'var(--text)',
            lineHeight: 0.95,
            margin: 0,
            letterSpacing: 2,
          }}
        >
          REVIEW PACKET
        </h1>
        <p
          style={{
            fontFamily: 'var(--body)',
            fontSize: '1rem',
            color: 'var(--text-mid)',
            marginTop: 16,
            maxWidth: 520,
            lineHeight: 1.6,
          }}
        >
          Build a formatted review packet ready to paste into App Store Connect.
        </p>
      </div>

      {!generated ? (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 40 }}>
          {/* ── App Info ── */}
          <div style={cardStyle}>
            <div style={sectionLabel}>// app info</div>
            <div
              style={{
                display: 'grid',
                gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
                gap: 20,
              }}
            >
              <InputField label="App Name" value={data.appName} onChange={(v) => update('appName', v)} placeholder="My App" />
              <InputField label="Bundle ID" value={data.bundleId} onChange={(v) => update('bundleId', v)} placeholder="com.company.app" />
              <InputField label="Version" value={data.version} onChange={(v) => update('version', v)} placeholder="1.0.0" />
            </div>
          </div>

          {/* ── Demo Credentials ── */}
          <div style={cardStyle}>
            <div style={sectionLabel}>// demo credentials</div>
            <div
              style={{
                display: 'grid',
                gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
                gap: 20,
              }}
            >
              <InputField label="Demo Email" value={data.demoEmail} onChange={(v) => update('demoEmail', v)} placeholder="demo@example.com" />
              <InputField label="Demo Password" value={data.demoPassword} onChange={(v) => update('demoPassword', v)} placeholder="testPassword123" type="text" />
            </div>
          </div>

          {/* ── Testing Instructions ── */}
          <div style={cardStyle}>
            <div style={sectionLabel}>// testing instructions</div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
              <TextAreaField
                label="Testing Steps (one per line)"
                value={data.testingSteps}
                onChange={(v) => update('testingSteps', v)}
                placeholder={"Launch the app\nTap Sign In\nEnter demo credentials\nNavigate to main feed\nTest all tab bar items"}
                rows={6}
              />
              <TextAreaField
                label="Special Instructions"
                value={data.specialInstructions}
                onChange={(v) => update('specialInstructions', v)}
                placeholder="Any additional context for the reviewer..."
                rows={3}
              />
            </div>
          </div>

          {/* ── Features ── */}
          <div style={cardStyle}>
            <div style={sectionLabel}>// features</div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
              <Toggle label="In-App Purchases" checked={data.hasIAP} onChange={(v) => update('hasIAP', v)} />
              {data.hasIAP && (
                <TextAreaField label="IAP Testing Instructions" value={data.iapInstructions} onChange={(v) => update('iapInstructions', v)} placeholder="How to test IAP in sandbox..." rows={2} />
              )}

              <Toggle label="Subscriptions" checked={data.hasSubscription} onChange={(v) => update('hasSubscription', v)} />
              {data.hasSubscription && (
                <TextAreaField label="Subscription Testing Instructions" value={data.subInstructions} onChange={(v) => update('subInstructions', v)} placeholder="How to test subscriptions..." rows={2} />
              )}

              <Toggle label="Requires Specific Hardware" checked={data.requiresHardware} onChange={(v) => update('requiresHardware', v)} />
              {data.requiresHardware && (
                <TextAreaField label="Hardware Notes" value={data.hardwareNotes} onChange={(v) => update('hardwareNotes', v)} placeholder="e.g. Requires Bluetooth accessory..." rows={2} />
              )}

              <Toggle label="Location-Based Features" checked={data.requiresLocation} onChange={(v) => update('requiresLocation', v)} />
              {data.requiresLocation && (
                <TextAreaField label="Location Notes" value={data.locationNotes} onChange={(v) => update('locationNotes', v)} placeholder="e.g. Set location to San Francisco..." rows={2} />
              )}
            </div>
          </div>

          {/* ── Generate button ── */}
          <div style={{ display: 'flex', justifyContent: 'flex-end' }}>
            <button
              onClick={handleGenerate}
              disabled={!data.appName.trim()}
              className="btn-primary"
              style={{
                padding: '14px 36px',
                fontFamily: 'var(--mono)',
                fontSize: '0.65rem',
                letterSpacing: 2,
                textTransform: 'uppercase',
                cursor: data.appName.trim() ? 'pointer' : 'not-allowed',
                borderRadius: 0,
              }}
            >
              Generate Packet
            </button>
          </div>
        </div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 40 }}>
          {/* ── Output ── */}
          <div style={{ border: '1px solid var(--border)' }}>
            <div
              style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'space-between',
                padding: '16px 32px',
                borderBottom: '1px solid var(--border)',
              }}
            >
              <div style={sectionLabel}>// generated packet</div>
              <button
                onClick={handleCopy}
                style={{
                  background: 'transparent',
                  border: '1px solid var(--border)',
                  padding: '8px 18px',
                  fontFamily: 'var(--mono)',
                  fontSize: '0.55rem',
                  letterSpacing: 2,
                  textTransform: 'uppercase',
                  color: copied ? 'var(--green)' : 'var(--text-mid)',
                  cursor: 'pointer',
                  borderRadius: 0,
                }}
              >
                {copied ? 'Copied!' : 'Copy to Clipboard'}
              </button>
            </div>
            <pre
              style={{
                padding: '28px 32px',
                fontFamily: 'var(--mono)',
                fontSize: '0.78rem',
                lineHeight: 1.7,
                color: 'rgba(255,255,255,0.8)',
                whiteSpace: 'pre-wrap',
                overflowX: 'auto',
                margin: 0,
              }}
            >
              {packetText}
            </pre>
          </div>

          {/* ── Actions ── */}
          <div style={{ display: 'flex', alignItems: 'center', gap: 16, justifyContent: 'center' }}>
            <button
              onClick={() => setGenerated(false)}
              style={{
                background: 'transparent',
                border: '1px solid var(--border)',
                padding: '14px 32px',
                fontFamily: 'var(--mono)',
                fontSize: '0.65rem',
                letterSpacing: 2,
                textTransform: 'uppercase',
                color: 'var(--text-mid)',
                cursor: 'pointer',
                borderRadius: 0,
              }}
            >
              Edit
            </button>
            <button
              onClick={handleCopy}
              className="btn-primary"
              style={{
                padding: '14px 32px',
                fontFamily: 'var(--mono)',
                fontSize: '0.65rem',
                letterSpacing: 2,
                textTransform: 'uppercase',
                cursor: 'pointer',
                borderRadius: 0,
              }}
            >
              {copied ? 'Copied!' : 'Copy for App Store Connect'}
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
