'use client';

import { useState } from 'react';

interface PacketData {
  appName: string;
  bundleId: string;
  version: string;
  demoEmail: string;
  demoPassword: string;
  testingSteps: string;
  specialInstructions: string;
  hasIAP: boolean;
  iapInstructions: string;
  hasSubscription: boolean;
  subInstructions: string;
  requiresHardware: boolean;
  hardwareNotes: string;
  requiresLocation: boolean;
  locationNotes: string;
}

const INITIAL: PacketData = {
  appName: '',
  bundleId: '',
  version: '',
  demoEmail: '',
  demoPassword: '',
  testingSteps: '',
  specialInstructions: '',
  hasIAP: false,
  iapInstructions: '',
  hasSubscription: false,
  subInstructions: '',
  requiresHardware: false,
  hardwareNotes: '',
  requiresLocation: false,
  locationNotes: '',
};

function generatePacketText(data: PacketData): string {
  const lines: string[] = [];

  lines.push('═══════════════════════════════════════');
  lines.push(`  APP STORE REVIEW PACKET`);
  lines.push(`  ${data.appName || 'Your App'} v${data.version || '1.0'}`);
  lines.push('═══════════════════════════════════════');
  lines.push('');

  if (data.bundleId) {
    lines.push(`Bundle ID: ${data.bundleId}`);
    lines.push('');
  }

  // Demo credentials
  lines.push('── DEMO ACCOUNT ──────────────────────');
  if (data.demoEmail && data.demoPassword) {
    lines.push(`Email:    ${data.demoEmail}`);
    lines.push(`Password: ${data.demoPassword}`);
  } else {
    lines.push('No login required for this app.');
  }
  lines.push('');

  // Testing steps
  lines.push('── TESTING STEPS ─────────────────────');
  if (data.testingSteps.trim()) {
    data.testingSteps.split('\n').forEach((step, i) => {
      const text = step.trim();
      if (text) lines.push(`${i + 1}. ${text}`);
    });
  } else {
    lines.push('1. Launch the app');
    lines.push('2. Log in with demo credentials above');
    lines.push('3. Navigate through all main features');
  }
  lines.push('');

  // IAP
  if (data.hasIAP) {
    lines.push('── IN-APP PURCHASES ──────────────────');
    lines.push(data.iapInstructions.trim() || 'In-app purchases are available. Please use the sandbox environment for testing.');
    lines.push('');
  }

  // Subscriptions
  if (data.hasSubscription) {
    lines.push('── SUBSCRIPTIONS ─────────────────────');
    lines.push(data.subInstructions.trim() || 'Subscription features can be tested in sandbox mode. Auto-renewal periods are shortened for testing.');
    lines.push('');
  }

  // Hardware
  if (data.requiresHardware) {
    lines.push('── HARDWARE REQUIREMENTS ─────────────');
    lines.push(data.hardwareNotes.trim() || 'This app requires specific hardware features. Please see notes below.');
    lines.push('');
  }

  // Location
  if (data.requiresLocation) {
    lines.push('── LOCATION REQUIREMENTS ─────────────');
    lines.push(data.locationNotes.trim() || 'This app uses location services. For testing, any location in the United States will work.');
    lines.push('');
  }

  // Special instructions
  if (data.specialInstructions.trim()) {
    lines.push('── ADDITIONAL NOTES ──────────────────');
    lines.push(data.specialInstructions.trim());
    lines.push('');
  }

  lines.push('═══════════════════════════════════════');
  lines.push(`Generated by Luminetic · ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}`);

  return lines.join('\n');
}

function InputField({ label, value, onChange, placeholder, type = 'text' }: {
  label: string; value: string; onChange: (v: string) => void; placeholder?: string; type?: string;
}) {
  return (
    <div>
      <label className="block text-[11px] tracking-[2px] uppercase mb-2" style={{ color: 'var(--gray)' }}>
        {label}
      </label>
      <input
        type={type}
        value={value}
        onChange={(e) => onChange(e.target.value)}
        placeholder={placeholder}
        className="input-field"
      />
    </div>
  );
}

function TextAreaField({ label, value, onChange, placeholder, rows = 4 }: {
  label: string; value: string; onChange: (v: string) => void; placeholder?: string; rows?: number;
}) {
  return (
    <div>
      <label className="block text-[11px] tracking-[2px] uppercase mb-2" style={{ color: 'var(--gray)' }}>
        {label}
      </label>
      <textarea
        value={value}
        onChange={(e) => onChange(e.target.value)}
        placeholder={placeholder}
        rows={rows}
        className="input-field resize-none leading-relaxed"
      />
    </div>
  );
}

function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (v: boolean) => void }) {
  return (
    <label className="flex items-center gap-3 cursor-pointer py-2">
      <div
        className="w-9 h-5 rounded-full relative transition-all duration-200 cursor-pointer"
        style={{ background: checked ? 'var(--pink)' : 'var(--border)' }}
        onClick={() => onChange(!checked)}
      >
        <div
          className="w-3.5 h-3.5 rounded-full bg-white absolute top-[3px] transition-all duration-200"
          style={{ left: checked ? '18px' : '3px' }}
        />
      </div>
      <span className="text-[13px]" style={{ color: checked ? 'var(--white)' : 'var(--gray)' }}>
        {label}
      </span>
    </label>
  );
}

export default function ReviewPacketPage() {
  const [data, setData] = useState<PacketData>(INITIAL);
  const [generated, setGenerated] = useState(false);
  const [packetText, setPacketText] = useState('');
  const [copied, setCopied] = useState(false);

  function update<K extends keyof PacketData>(key: K, value: PacketData[K]) {
    setData((prev) => ({ ...prev, [key]: value }));
  }

  function handleGenerate() {
    const text = generatePacketText(data);
    setPacketText(text);
    setGenerated(true);
  }

  function handleCopy() {
    navigator.clipboard.writeText(packetText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  return (
    <div className="w-full px-6 md:px-12 lg:px-20 pt-28 pb-20">
      <div className="mb-10">
        <div className="text-[11px] font-medium tracking-[5px] uppercase mb-2" style={{ color: 'var(--pink)' }}>
          Review Packet
        </div>
        <h1 className="text-[11px] font-medium tracking-[5px] uppercase" style={{ color: 'var(--white)' }}>
          Generate Review Notes
        </h1>
        <p className="text-[14px] mt-2" style={{ color: 'var(--gray)' }}>
          Build a formatted review packet ready to paste into App Store Connect.
        </p>
      </div>

      {!generated ? (
        <div className="flex flex-col gap-8">
          {/* App Info */}
          <div
            className="glass-card p-6 relative overflow-hidden"
          >
            <div className="glow-line" />
            <div className="text-[10px] tracking-[3px] uppercase mb-5" style={{ color: 'var(--pink)' }}>App Info</div>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <InputField label="App Name" value={data.appName} onChange={(v) => update('appName', v)} placeholder="My App" />
              <InputField label="Bundle ID" value={data.bundleId} onChange={(v) => update('bundleId', v)} placeholder="com.company.app" />
              <InputField label="Version" value={data.version} onChange={(v) => update('version', v)} placeholder="1.0.0" />
            </div>
          </div>

          {/* Demo Credentials */}
          <div
            className="glass-card p-6 relative overflow-hidden"
          >
            <div className="glow-line" />
            <div className="text-[10px] tracking-[3px] uppercase mb-5" style={{ color: 'var(--pink)' }}>Demo Credentials</div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <InputField label="Demo Email" value={data.demoEmail} onChange={(v) => update('demoEmail', v)} placeholder="demo@example.com" />
              <InputField label="Demo Password" value={data.demoPassword} onChange={(v) => update('demoPassword', v)} placeholder="testPassword123" type="text" />
            </div>
          </div>

          {/* Testing Steps */}
          <div
            className="glass-card p-6 relative overflow-hidden"
          >
            <div className="glow-line" />
            <div className="text-[10px] tracking-[3px] uppercase mb-5" style={{ color: 'var(--pink)' }}>Testing Instructions</div>
            <TextAreaField
              label="Testing Steps (one per line)"
              value={data.testingSteps}
              onChange={(v) => update('testingSteps', v)}
              placeholder={"Launch the app\nTap Sign In\nEnter demo credentials\nNavigate to main feed\nTest all tab bar items"}
              rows={6}
            />
            <div className="mt-4">
              <TextAreaField
                label="Special Instructions"
                value={data.specialInstructions}
                onChange={(v) => update('specialInstructions', v)}
                placeholder="Any additional context for the reviewer..."
                rows={3}
              />
            </div>
          </div>

          {/* Feature Toggles */}
          <div
            className="glass-card p-6 relative overflow-hidden"
          >
            <div className="glow-line" />
            <div className="text-[10px] tracking-[3px] uppercase mb-5" style={{ color: 'var(--pink)' }}>Features</div>

            <div className="flex flex-col gap-3">
              <Toggle label="In-App Purchases" checked={data.hasIAP} onChange={(v) => update('hasIAP', v)} />
              {data.hasIAP && (
                <TextAreaField label="IAP Testing Instructions" value={data.iapInstructions} onChange={(v) => update('iapInstructions', v)} placeholder="How to test IAP in sandbox..." rows={2} />
              )}

              <Toggle label="Subscriptions" checked={data.hasSubscription} onChange={(v) => update('hasSubscription', v)} />
              {data.hasSubscription && (
                <TextAreaField label="Subscription Testing Instructions" value={data.subInstructions} onChange={(v) => update('subInstructions', v)} placeholder="How to test subscriptions..." rows={2} />
              )}

              <Toggle label="Requires Specific Hardware" checked={data.requiresHardware} onChange={(v) => update('requiresHardware', v)} />
              {data.requiresHardware && (
                <TextAreaField label="Hardware Notes" value={data.hardwareNotes} onChange={(v) => update('hardwareNotes', v)} placeholder="e.g. Requires Bluetooth accessory..." rows={2} />
              )}

              <Toggle label="Location-Based Features" checked={data.requiresLocation} onChange={(v) => update('requiresLocation', v)} />
              {data.requiresLocation && (
                <TextAreaField label="Location Notes" value={data.locationNotes} onChange={(v) => update('locationNotes', v)} placeholder="e.g. Set location to San Francisco..." rows={2} />
              )}
            </div>
          </div>

          {/* Generate */}
          <div className="flex justify-end">
            <button
              onClick={handleGenerate}
              disabled={!data.appName.trim()}
              className="btn-primary px-8 py-3.5 text-[12px] tracking-[2px] uppercase cursor-pointer"
            >
              Generate Packet
            </button>
          </div>
        </div>
      ) : (
        <div className="flex flex-col gap-6">
          {/* Output */}
          <div className="glass-card relative overflow-hidden">
            <div className="glow-line" />
            <div className="flex items-center justify-between px-6 py-4 border-b" style={{ borderColor: 'var(--border)' }}>
              <div className="text-[11px] tracking-[3px] uppercase" style={{ color: 'var(--pink)' }}>
                Generated Packet
              </div>
              <button
                onClick={handleCopy}
                className="btn-secondary px-4 py-2 text-[11px] tracking-[1.5px] uppercase cursor-pointer"
                style={{ color: copied ? '#34d399' : undefined }}
              >
                {copied ? 'Copied!' : 'Copy to Clipboard'}
              </button>
            </div>
            <pre
              className="px-6 py-5 text-[13px] leading-relaxed overflow-x-auto whitespace-pre-wrap"
              style={{ color: 'rgba(255,255,255,0.8)', fontFamily: "'SF Mono', 'Fira Code', monospace" }}
            >
              {packetText}
            </pre>
          </div>

          {/* Actions */}
          <div className="flex items-center gap-4 justify-center">
            <button
              onClick={() => setGenerated(false)}
              className="btn-secondary px-6 py-3 text-[12px] tracking-[2px] uppercase cursor-pointer"
            >
              Edit
            </button>
            <button
              onClick={handleCopy}
              className="btn-primary px-6 py-3 text-[12px] tracking-[2px] uppercase cursor-pointer"
            >
              {copied ? 'Copied!' : 'Copy for App Store Connect'}
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
