import Header from '@/components/Header';
import Footer from '@/components/Footer';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms and Conditions | Luminetic',
  description: 'Terms and Conditions of Service for Luminetic.io, operated by SLTR Digital LLC.',
};

export default function TermsPage() {
  return (
    <div style={{ background: 'var(--bg)', minHeight: '100vh' }}>
      <div className="grid-bg" />
      <Header />

      <main style={{
        maxWidth: 800,
        margin: '0 auto',
        padding: '140px 32px 80px',
        position: 'relative',
        zIndex: 1,
      }}>
        <div style={{
          fontFamily: 'var(--mono)',
          fontSize: '0.58rem',
          letterSpacing: 4,
          textTransform: 'uppercase',
          color: 'var(--orange)',
          marginBottom: 16,
        }}>
          // legal
        </div>
        <h1 style={{
          fontFamily: 'var(--display)',
          fontSize: 'clamp(1.8rem, 4vw, 2.6rem)',
          letterSpacing: 2,
          lineHeight: 1.1,
          margin: '0 0 12px',
          color: 'var(--text)',
        }}>
          TERMS AND CONDITIONS
        </h1>
        <p style={{
          fontFamily: 'var(--body)',
          fontSize: '0.82rem',
          color: 'var(--text-dim)',
          margin: '0 0 48px',
        }}>
          Effective March 28, 2026 &middot; Last updated March 28, 2026
        </p>

        <article className="terms-content" style={{
          fontFamily: 'var(--body)',
          fontSize: '0.88rem',
          lineHeight: 1.75,
          color: 'var(--text-mid)',
        }}>
          <p style={capsStyle}>
            PLEASE READ THESE TERMS AND CONDITIONS OF SERVICE (&ldquo;TERMS&rdquo;) CAREFULLY BEFORE USING LUMINETIC.IO (&ldquo;SERVICE&rdquo;). BY CREATING AN ACCOUNT, CLICKING &ldquo;I AGREE,&rdquo; OR OTHERWISE ACCESSING OR USING THE SERVICE, YOU (&ldquo;USER,&rdquo; &ldquo;YOU,&rdquo; &ldquo;YOUR&rdquo;) ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THESE TERMS. IF YOU DO NOT AGREE TO THESE TERMS, YOU MUST NOT CREATE AN ACCOUNT OR USE THE SERVICE.
          </p>
          <p style={capsStyle}>
            IF YOU ARE USING THE SERVICE ON BEHALF OF A COMPANY, ORGANIZATION, OR OTHER ENTITY, YOU REPRESENT AND WARRANT THAT YOU HAVE THE AUTHORITY TO BIND THAT ENTITY TO THESE TERMS, AND &ldquo;YOU&rdquo; AND &ldquo;YOUR&rdquo; SHALL REFER TO THAT ENTITY.
          </p>

          <SectionTitle num="1">Definitions</SectionTitle>
          <p><strong>&ldquo;Account&rdquo;</strong> means the registered user account you create to access the Service.</p>
          <p><strong>&ldquo;Analysis Report&rdquo;</strong> or <strong>&ldquo;Scan Results&rdquo;</strong> means the output generated by the Service after processing your Uploaded File, including severity classifications, issue descriptions, and remediation guidance.</p>
          <p><strong>&ldquo;Credit&rdquo;</strong> means a single unit of value that entitles you to one (1) scan of one (1) IPA file through the Service.</p>
          <p><strong>&ldquo;IPA File&rdquo;</strong> or <strong>&ldquo;Uploaded File&rdquo;</strong> means the iOS App Store Package file (.ipa) you upload to the Service for analysis.</p>
          <p><strong>&ldquo;Service&rdquo;</strong> means the Luminetic.io web-based application, including all associated features, tools, APIs, and interfaces operated by SLTR Digital LLC.</p>
          <p><strong>&ldquo;SLTR Digital LLC,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; &ldquo;our&rdquo;</strong> means SLTR Digital LLC, a limited liability company organized under the laws of the State of California, with its principal place of business in Los Angeles, California.</p>

          <SectionTitle num="2">Eligibility</SectionTitle>
          <p>2.1. You must be at least eighteen (18) years of age, or the age of legal majority in your jurisdiction, whichever is greater, to use the Service.</p>
          <p>2.2. You must have the legal capacity to enter into a binding agreement.</p>
          <p>2.3. You must not be a person barred from using the Service under the laws of the United States or any other applicable jurisdiction.</p>
          <p>2.4. You must not have had a Luminetic account previously terminated by us for violation of these Terms.</p>
          <p>2.5. If you are using the Service on behalf of an entity, you represent and warrant that you are authorized to accept these Terms on the entity&rsquo;s behalf and that the entity agrees to be responsible to us if you violate these Terms.</p>

          <SectionTitle num="3">Account Registration and Security</SectionTitle>
          <p>3.1. <strong>Registration Required.</strong> You must create an account to use the Service. Account creation requires a valid email address and authentication through our identity provider.</p>
          <p>3.2. <strong>Accurate Information.</strong> You agree to provide truthful, accurate, current, and complete information during registration. You agree to update your information promptly if it changes.</p>
          <p>3.3. <strong>Account Security.</strong> You are solely responsible for maintaining the confidentiality of your account credentials, including your password and any authentication tokens. You agree to notify us immediately at support@luminetic.io if you become aware of any unauthorized access to or use of your account.</p>
          <p>3.4. <strong>Account Responsibility.</strong> You are fully responsible for all activities that occur under your account, whether or not authorized by you. We are not liable for any loss or damage arising from your failure to secure your account credentials.</p>
          <p>3.5. <strong>One Account Per User.</strong> Each individual or entity may maintain only one (1) active account. Creating multiple accounts to obtain additional complimentary credits or to circumvent any limitation of the Service is a violation of these Terms and grounds for immediate termination.</p>
          <p>3.6. <strong>Account Non-Transferability.</strong> Your account is personal to you and may not be assigned, transferred, sold, or shared with any other person or entity without our prior written consent.</p>

          <SectionTitle num="4">Service Description</SectionTitle>
          <p>4.1. <strong>What the Service Does.</strong> Luminetic is an AI-powered analysis platform that scans iOS application package files (IPA files) against Apple&rsquo;s App Store Review Guidelines. The Service uses multiple artificial intelligence models operating in parallel to evaluate your application and provide feedback categorized by severity level: Critical, Major, Medium, and Minor.</p>
          <p>4.2. <strong>What the Service Does Not Do.</strong> The Service does not:</p>
          <ul>
            <li>Guarantee approval of your application by Apple Inc. or any other app store or review body.</li>
            <li>Submit your application to any app store on your behalf.</li>
            <li>Modify, alter, recompile, or change your IPA file in any way.</li>
            <li>Provide legal advice, compliance certification, or regulatory approval.</li>
            <li>Replace human review, quality assurance testing, or professional app store optimization services.</li>
            <li>Guarantee detection of all potential review issues, violations, or deficiencies.</li>
          </ul>
          <p>4.3. <strong>No Affiliation with Apple.</strong> Luminetic is an independent product. It is not affiliated with, endorsed by, sponsored by, or in any way officially connected to Apple Inc. or any of its subsidiaries or affiliates. &ldquo;Apple,&rdquo; &ldquo;iOS,&rdquo; &ldquo;App Store,&rdquo; and &ldquo;IPA&rdquo; are trademarks of Apple Inc. References to Apple&rsquo;s review guidelines are for descriptive purposes only.</p>
          <p>4.4. <strong>AI Limitations.</strong> The Service relies on artificial intelligence models that, while sophisticated, may produce results that are inaccurate, incomplete, outdated, or inapplicable to your specific application. AI-generated analysis is probabilistic, not deterministic. Different scans of the same file may produce slightly different results. You acknowledge and accept these inherent limitations.</p>
          <p>4.5. <strong>Guideline Currency.</strong> Apple&rsquo;s App Store Review Guidelines are subject to change at any time without notice to us. While we endeavor to keep our analysis models current, there may be periods during which the Service does not reflect the most recently published version of Apple&rsquo;s guidelines.</p>

          <SectionTitle num="5">Credits and Payment</SectionTitle>
          <p>5.1. <strong>Credit-Based System.</strong> The Service operates exclusively on a credit-based system. There are no subscription plans, recurring charges, or automatic billing. You purchase credits and use them at your discretion.</p>
          <p>5.2. <strong>Credit Consumption.</strong> Each scan of one (1) IPA file consumes one (1) credit. A credit is consumed when the scan process initiates. Partial scans, failed scans due to unsupported file formats, or scans that do not complete due to issues with your Uploaded File will still consume a credit unless the failure is caused by a confirmed error on our end.</p>
          <p>5.3. <strong>Complimentary Credit.</strong> Upon successful creation of a new account, you will receive one (1) complimentary scan credit at no charge. This complimentary credit is non-transferable, has no cash value, and is limited to one per user or entity. Abuse of this offer (including creating multiple accounts to obtain additional free credits) is grounds for immediate termination of all associated accounts.</p>
          <p>5.4. <strong>Purchasing Credits.</strong> Additional credits may be purchased through the Service in predefined bundles. All payments are processed securely by Square, Inc. (&ldquo;Square&rdquo;), a third-party payment processor. By making a purchase, you also agree to Square&rsquo;s terms of service and privacy policy, which are available on Square&rsquo;s website.</p>
          <p>5.5. <strong>Pricing.</strong> Credit bundle pricing is displayed on the Service at the time of purchase. We reserve the right to change pricing at any time. Price changes do not affect credits already purchased.</p>
          <p>5.6. <strong>Credit Expiration.</strong> Purchased credits do not expire.</p>
          <p>5.7. <strong>No Refunds.</strong> ALL PURCHASES ARE FINAL AND NON-REFUNDABLE. Due to the digital nature of the Service, credits cannot be refunded, exchanged, or converted to cash once purchased. If a scan fails due to a confirmed technical error on our infrastructure (not caused by the user&rsquo;s file, network, or browser), we will, at our sole discretion, restore the consumed credit to your account. You must report such failures to support@luminetic.io within seven (7) days of the failed scan.</p>
          <p>5.8. <strong>Taxes.</strong> Prices displayed may not include applicable sales tax, value-added tax, or other government-imposed charges. You are responsible for all taxes associated with your purchases, except for taxes based on our net income.</p>
          <p>5.9. <strong>Payment Disputes.</strong> If you believe a charge is incorrect, you must contact us at support@luminetic.io within thirty (30) days of the charge. Chargebacks or payment disputes filed without first contacting us may result in immediate account suspension.</p>

          <SectionTitle num="6">File Upload, Processing, and Data Handling</SectionTitle>
          <p style={capsStyle}>THIS SECTION DESCRIBES HOW WE HANDLE YOUR UPLOADED FILES. PLEASE READ IT CAREFULLY.</p>
          <p>6.1. <strong>File Upload.</strong> To use the scan feature, you must upload an IPA file through the Service&rsquo;s web interface. You are responsible for ensuring that the file you upload is a valid IPA file and that you have the legal right to upload and analyze it.</p>
          <p>6.2. <strong>Ownership of Uploaded Files.</strong> You retain full ownership of your IPA files and all intellectual property contained within them at all times. Uploading a file to the Service does not transfer any ownership rights to us.</p>
          <p>6.3. <strong>Limited License Grant.</strong> By uploading a file, you grant SLTR Digital LLC a limited, non-exclusive, non-transferable, revocable license to access, process, and analyze the file solely for the purpose of performing the scan you requested. This license terminates automatically upon deletion of the file from our systems.</p>

          <p>6.4. <strong>Immediate Deletion Policy.</strong></p>
          <ul>
            <li>Your Uploaded File is processed in memory during the active scan. Upon completion of the scan, the Uploaded File is automatically and permanently deleted from our servers. We do not retain your IPA file after the analysis is complete.</li>
            <li>Deletion occurs immediately upon scan completion, regardless of whether the scan was successful or encountered errors. There is no retention period.</li>
            <li>This deletion is irreversible. Once a scan is complete, the IPA file cannot be recovered, re-scanned, or re-downloaded. If you wish to perform another scan, you must upload the file again.</li>
            <li>Scan Results (the analysis report) are retained in your account separately and independently from the Uploaded File. Your analysis reports remain accessible in your account after the Uploaded File is deleted. Scan Results do not contain the IPA file itself or any binary data from it.</li>
          </ul>

          <p>6.5. <strong>What We Do Not Do With Your Files.</strong></p>
          <ul>
            <li>We do NOT sell, license, rent, share, distribute, or transfer your Uploaded Files or any data extracted from them to any third party for any reason.</li>
            <li>We do NOT use your Uploaded Files to train, fine-tune, or improve any artificial intelligence or machine learning models.</li>
            <li>We do NOT extract, copy, store, or retain source code, application assets, binary executables, cryptographic keys, certificates, provisioning profiles, user data, or any proprietary information from your Uploaded Files beyond what is strictly necessary to perform the analysis during the active scan process.</li>
            <li>We do NOT reverse-engineer, decompile, or disassemble your application.</li>
            <li>We do NOT access, read, or store any user data, personal information, or analytics data that may be contained within your application.</li>
            <li>We do NOT create backup copies, snapshots, or replicas of your Uploaded Files at any point during or after the scan process.</li>
          </ul>

          <p>6.6. <strong>Security Measures.</strong> We implement commercially reasonable technical and organizational security measures to protect Uploaded Files during transmission and processing, including encryption in transit (TLS). Since Uploaded Files are deleted immediately upon scan completion, at-rest encryption of Uploaded Files is not applicable. However, no method of electronic transmission is completely secure, and we cannot guarantee absolute security during the upload and processing window.</p>
          <p>6.7. <strong>Breach Notification.</strong> In the event of a data breach affecting your data (including Scan Results or account information), we will notify you at the email address associated with your account within seventy-two (72) hours of becoming aware of the breach and will take immediate steps to mitigate the impact. Because Uploaded Files are deleted immediately upon scan completion, the risk of IPA file exposure from a breach is limited to the brief processing window during which the scan is actively running.</p>
          <p>6.8. <strong>Your Responsibility.</strong> You acknowledge that by uploading an IPA file, you are transmitting a compiled application binary over the internet. You are solely responsible for:</p>
          <ul>
            <li>Ensuring you have the legal right to upload the file (see Section 7).</li>
            <li>Removing or redacting any sensitive data, credentials, API keys, or secrets embedded in your application before uploading, to the extent practical.</li>
            <li>Understanding that any data contained within the IPA file is transmitted to our servers for processing and is deleted immediately upon scan completion.</li>
          </ul>

          <SectionTitle num="7">Representations and Warranties Regarding Uploaded Files</SectionTitle>
          <p>By uploading an IPA file to the Service, you represent and warrant that:</p>
          <p>7.1. You are the developer of the application, an authorized representative of the developer, or have obtained explicit written permission from the rights holder to upload and analyze the file.</p>
          <p>7.2. The file does not contain any malware, viruses, trojans, ransomware, spyware, or other malicious code intended to compromise, damage, or gain unauthorized access to the Service or any other system.</p>
          <p>7.3. The file does not contain child sexual abuse material (CSAM), content that exploits minors, or any material that is illegal under United States federal law or California state law.</p>
          <p>7.4. The upload and analysis of the file does not violate any applicable law, regulation, contractual obligation, or third-party right, including but not limited to intellectual property rights, trade secrets, and non-disclosure agreements.</p>
          <p>7.5. If the application was developed under a work-for-hire arrangement, employment agreement, or contractor agreement, you have obtained all necessary authorizations to upload the file to a third-party analysis service.</p>
          <p>7.6. You understand that violation of these representations may result in immediate account termination and may expose you to legal liability.</p>

          <SectionTitle num="8">Prohibited Conduct</SectionTitle>
          <p>You agree not to engage in any of the following conduct:</p>
          <p>8.1. Uploading any file you do not have the legal right to analyze, including applications developed by third parties without their authorization.</p>
          <p>8.2. Uploading files containing malicious code, malware, or any software designed to damage, interfere with, or gain unauthorized access to the Service or any other computer system.</p>
          <p>8.3. Attempting to reverse-engineer, decompile, disassemble, or derive the source code, algorithms, or underlying technology of the Service.</p>
          <p>8.4. Attempting to access, probe, or test the vulnerability of the Service or any related system or network, or to breach any security or authentication measures.</p>
          <p>8.5. Using automated tools, bots, scrapers, crawlers, or scripts to access, interact with, or extract data from the Service without our prior written consent.</p>
          <p>8.6. Creating multiple accounts to circumvent credit limits, abuse the complimentary credit offer, or evade account termination.</p>
          <p>8.7. Interfering with or disrupting the Service, servers, or networks connected to the Service.</p>
          <p>8.8. Impersonating any person or entity, or falsely stating or misrepresenting your affiliation with any person or entity.</p>
          <p>8.9. Using the Service for any purpose that is illegal, fraudulent, or harmful.</p>
          <p>8.10. Attempting to resell, sublicense, or commercially redistribute access to the Service or its scan results without our prior written consent.</p>
          <p>8.11. Circumventing, disabling, or interfering with any security-related features of the Service.</p>

          <SectionTitle num="9">Intellectual Property</SectionTitle>
          <p>9.1. <strong>Your Intellectual Property.</strong> As stated in Section 6.2, you retain all ownership rights to your Uploaded Files and any intellectual property contained within them. Nothing in these Terms transfers any intellectual property rights from you to us, except for the limited license described in Section 6.3.</p>
          <p>9.2. <strong>Our Intellectual Property.</strong> The Service, including but not limited to its software, code, algorithms, AI models, user interface, design, graphics, logos, trademarks, trade names (&ldquo;Luminetic,&rdquo; &ldquo;SLTR Digital&rdquo;), documentation, and all other content and materials provided through the Service, are the exclusive property of SLTR Digital LLC and are protected by United States and international copyright, trademark, patent, trade secret, and other intellectual property or proprietary rights laws.</p>
          <p>9.3. <strong>Limited Use License.</strong> Subject to your compliance with these Terms, we grant you a limited, non-exclusive, non-transferable, revocable license to access and use the Service for its intended purpose. This license does not include the right to:</p>
          <ul>
            <li>Modify, copy, or create derivative works of the Service or any part thereof.</li>
            <li>Sell, resell, license, sublicense, distribute, rent, or lease the Service.</li>
            <li>Use the Service to build a competing product or service.</li>
            <li>Publicly display, perform, or transmit any part of the Service without our prior written consent.</li>
          </ul>
          <p>9.4. <strong>Feedback.</strong> If you provide us with any suggestions, ideas, feedback, or recommendations regarding the Service (&ldquo;Feedback&rdquo;), you grant us a worldwide, perpetual, irrevocable, royalty-free, fully sublicensable license to use, reproduce, modify, and incorporate such Feedback into the Service without any obligation or compensation to you.</p>
          <p>9.5. <strong>Scan Results Ownership.</strong> Analysis Reports generated by the Service based on your Uploaded Files are yours to use, share, and reference as you see fit. However, the underlying methodology, algorithms, scoring systems, and analytical frameworks used to generate those reports remain the exclusive intellectual property of SLTR Digital LLC.</p>

          <SectionTitle num="10">Privacy</SectionTitle>
          <p>10.1. <strong>Privacy Policy.</strong> Our collection, use, and disclosure of personal information in connection with the Service is described in our Privacy Policy, which is incorporated into these Terms by reference. By using the Service, you consent to the practices described in the Privacy Policy.</p>
          <p>10.2. <strong>Account Data.</strong> We collect and store the information you provide during registration (email address and authentication data) for the purpose of providing the Service.</p>
          <p>10.3. <strong>Usage Data.</strong> We may collect anonymized, aggregated usage data (such as number of scans performed, feature usage patterns, and error rates) to improve the Service. This data does not include your Uploaded Files, their contents, or any personally identifiable information extracted from your applications.</p>
          <p>10.4. <strong>No Sale of Personal Data.</strong> We do not sell your personal information to third parties.</p>

          <SectionTitle num="11">Third-Party Services</SectionTitle>
          <p>11.1. The Service integrates with and relies upon third-party services, including but not limited to:</p>
          <ul>
            <li><strong>Square, Inc.</strong> for payment processing.</li>
            <li><strong>Amazon Web Services (AWS)</strong> for cloud infrastructure and hosting.</li>
            <li><strong>Third-party AI model providers</strong> for analysis processing.</li>
            <li><strong>Authentication providers</strong> for identity verification.</li>
          </ul>
          <p>11.2. Your use of the Service may be subject to the terms and conditions of these third-party services. We are not responsible for the practices, policies, or availability of any third-party service.</p>
          <p>11.3. We are not liable for any loss, damage, or inconvenience caused by the unavailability or malfunction of any third-party service.</p>

          <SectionTitle num="12">Disclaimer of Warranties</SectionTitle>
          <p style={capsStyle}>12.1. THE SERVICE IS PROVIDED ON AN &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED.</p>
          <p style={capsStyle}>12.2. TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, SLTR DIGITAL LLC EXPRESSLY DISCLAIMS ALL WARRANTIES, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING BUT NOT LIMITED TO:</p>
          <ul style={capsStyle}>
            <li>IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.</li>
            <li>WARRANTIES ARISING FROM COURSE OF DEALING, COURSE OF PERFORMANCE, OR USAGE OF TRADE.</li>
            <li>ANY WARRANTY THAT THE SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE, ERROR-FREE, OR FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.</li>
            <li>ANY WARRANTY THAT THE RESULTS OBTAINED FROM THE SERVICE WILL BE ACCURATE, RELIABLE, COMPLETE, OR CURRENT.</li>
            <li>ANY WARRANTY THAT DEFECTS IN THE SERVICE WILL BE CORRECTED.</li>
          </ul>
          <p style={capsStyle}>12.3. YOU ACKNOWLEDGE AND AGREE THAT:</p>
          <ul style={capsStyle}>
            <li>AI-GENERATED ANALYSIS IS INHERENTLY IMPERFECT AND SHOULD BE USED AS ONE INPUT AMONG MANY IN YOUR APP STORE SUBMISSION PROCESS.</li>
            <li>APPLE&rsquo;S REVIEW PROCESS INVOLVES HUMAN REVIEWERS WHO MAY APPLY SUBJECTIVE JUDGMENT THAT CANNOT BE PREDICTED BY AUTOMATED ANALYSIS.</li>
            <li>A &ldquo;CLEAN&rdquo; SCAN RESULT (NO ISSUES FOUND) DOES NOT GUARANTEE APP STORE APPROVAL.</li>
            <li>AN &ldquo;ISSUE FOUND&rdquo; SCAN RESULT DOES NOT NECESSARILY MEAN YOUR APP WILL BE REJECTED.</li>
            <li>YOU ARE SOLELY RESPONSIBLE FOR ALL DECISIONS REGARDING YOUR APPLICATION AND ITS SUBMISSION TO ANY APP STORE.</li>
          </ul>

          <SectionTitle num="13">Limitation of Liability</SectionTitle>
          <p style={capsStyle}>13.1. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL SLTR DIGITAL LLC, ITS OFFICERS, DIRECTORS, MEMBERS, EMPLOYEES, AGENTS, CONTRACTORS, AFFILIATES, OR LICENSORS BE LIABLE FOR ANY:</p>
          <ul style={capsStyle}>
            <li>INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES.</li>
            <li>LOSS OF PROFITS, REVENUE, BUSINESS, SAVINGS, GOODWILL, OR ANTICIPATED SAVINGS.</li>
            <li>LOSS OF DATA, INCLUDING BUT NOT LIMITED TO LOSS OF YOUR UPLOADED FILES.</li>
            <li>BUSINESS INTERRUPTION OR LOSS OF BUSINESS OPPORTUNITY.</li>
            <li>APP STORE REJECTION OR DELAYED APPROVAL.</li>
            <li>DAMAGES ARISING FROM RELIANCE ON SCAN RESULTS OR ANALYSIS REPORTS.</li>
            <li>COST OF PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES.</li>
            <li>DAMAGES RESULTING FROM UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA.</li>
          </ul>
          <p style={capsStyle}>WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY, OR ANY OTHER LEGAL THEORY, WHETHER OR NOT WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
          <p style={capsStyle}>13.2. <strong>AGGREGATE LIABILITY CAP.</strong> OUR TOTAL AGGREGATE LIABILITY FOR ALL CLAIMS ARISING FROM OR RELATING TO THESE TERMS OR YOUR USE OF THE SERVICE SHALL NOT EXCEED THE GREATER OF: (A) THE TOTAL AMOUNT YOU HAVE PAID TO US IN THE TWELVE (12) MONTHS IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE CLAIM, OR (B) FIFTY DOLLARS ($50.00 USD).</p>
          <p style={capsStyle}>13.3. <strong>ESSENTIAL PURPOSE.</strong> THE LIMITATIONS OF LIABILITY SET FORTH IN THIS SECTION SHALL APPLY EVEN IF A REMEDY SET FORTH HEREIN IS FOUND TO HAVE FAILED ITS ESSENTIAL PURPOSE.</p>
          <p>13.4. <strong>Jurisdictional Limitations.</strong> Some jurisdictions do not allow the exclusion or limitation of certain damages. If these laws apply to you, some or all of the above exclusions or limitations may not apply, and you may have additional rights.</p>

          <SectionTitle num="14">Indemnification</SectionTitle>
          <p>14.1. You agree to indemnify, defend, and hold harmless SLTR Digital LLC and its officers, directors, members, employees, agents, contractors, affiliates, and licensors (collectively, &ldquo;Indemnified Parties&rdquo;) from and against any and all claims, demands, actions, damages, losses, liabilities, judgments, settlements, costs, and expenses (including reasonable attorneys&rsquo; fees and legal costs) arising from or relating to:</p>
          <ul>
            <li>Your use or misuse of the Service.</li>
            <li>Your violation of these Terms.</li>
            <li>Your violation of any applicable law, regulation, or third-party right.</li>
            <li>Your Uploaded Files, including any claim that an Uploaded File infringes or misappropriates the intellectual property or other rights of any third party.</li>
            <li>Any dispute between you and a third party relating to the Service.</li>
          </ul>
          <p>14.2. We reserve the right, at your expense, to assume the exclusive defense and control of any matter subject to indemnification by you, in which case you agree to cooperate with our defense of such claim.</p>

          <SectionTitle num="15">Dispute Resolution</SectionTitle>
          <p>15.1. <strong>Informal Resolution.</strong> Before filing any formal legal action, you agree to first attempt to resolve any dispute, claim, or controversy arising from or relating to these Terms or the Service (&ldquo;Dispute&rdquo;) by contacting us at support@luminetic.io. We will attempt to resolve the Dispute informally within thirty (30) days.</p>
          <p style={capsStyle}>15.2. <strong>BINDING ARBITRATION.</strong> IF THE DISPUTE IS NOT RESOLVED INFORMALLY WITHIN THIRTY (30) DAYS, YOU AND SLTR DIGITAL LLC AGREE TO RESOLVE THE DISPUTE THROUGH BINDING INDIVIDUAL ARBITRATION ADMINISTERED BY THE AMERICAN ARBITRATION ASSOCIATION (&ldquo;AAA&rdquo;) UNDER ITS COMMERCIAL ARBITRATION RULES. THE ARBITRATION SHALL BE CONDUCTED BY A SINGLE ARBITRATOR IN LOS ANGELES COUNTY, CALIFORNIA, OR, AT YOUR ELECTION, VIA TELEPHONE OR VIDEO CONFERENCE. THE ARBITRATOR&rsquo;S DECISION SHALL BE FINAL AND BINDING AND MAY BE ENTERED AS A JUDGMENT IN ANY COURT OF COMPETENT JURISDICTION.</p>
          <p style={capsStyle}>15.3. <strong>CLASS ACTION WAIVER.</strong> YOU AND SLTR DIGITAL LLC AGREE THAT EACH PARTY MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR ITS INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS, CONSOLIDATED, OR REPRESENTATIVE PROCEEDING. THE ARBITRATOR MAY NOT CONSOLIDATE MORE THAN ONE PERSON&rsquo;S CLAIMS AND MAY NOT PRESIDE OVER ANY FORM OF A REPRESENTATIVE OR CLASS PROCEEDING.</p>
          <p>15.4. <strong>Exceptions.</strong> Notwithstanding the above, either party may seek injunctive or other equitable relief in any court of competent jurisdiction to prevent the actual or threatened infringement, misappropriation, or violation of intellectual property rights.</p>
          <p>15.5. <strong>Opt-Out.</strong> You may opt out of the arbitration and class action waiver provisions by sending written notice to support@luminetic.io within thirty (30) days of creating your account. Your notice must include your name, email address, and a clear statement that you wish to opt out of arbitration.</p>

          <SectionTitle num="16">Termination</SectionTitle>
          <p>16.1. <strong>Termination by You.</strong> You may stop using the Service and delete your account at any time. Upon account deletion, your Scan Results and any associated data will be removed in accordance with our data retention practices. Any unused purchased credits at the time of voluntary account deletion are forfeited and non-refundable.</p>
          <p>16.2. <strong>Termination by Us.</strong> We reserve the right to suspend or terminate your account and access to the Service at any time, with or without cause, with or without prior notice, including but not limited to situations where:</p>
          <ul>
            <li>You violate these Terms or any applicable law.</li>
            <li>You engage in Prohibited Conduct as described in Section 8.</li>
            <li>We are required to do so by law or regulation.</li>
            <li>We discontinue the Service in whole or in part.</li>
          </ul>
          <p>16.3. <strong>Effect of Termination.</strong> Upon termination:</p>
          <ul>
            <li>Your right to access and use the Service ceases immediately.</li>
            <li>Any unused credits are forfeited if termination is due to your violation of these Terms.</li>
            <li>Sections that by their nature should survive termination shall survive, including but not limited to Sections 6.5, 7, 9, 12, 13, 14, 15, and 17.</li>
            <li>Because Uploaded Files are deleted immediately upon scan completion under normal operation, no additional file deletion is required upon termination.</li>
          </ul>

          <SectionTitle num="17">General Provisions</SectionTitle>
          <p>17.1. <strong>Governing Law.</strong> These Terms shall be governed by and construed in accordance with the laws of the State of California, United States of America, without regard to its conflict of law provisions. To the extent litigation is permitted under Section 15, the exclusive jurisdiction and venue shall be the state and federal courts located in Los Angeles County, California.</p>
          <p>17.2. <strong>Entire Agreement.</strong> These Terms, together with our Privacy Policy and any other policies or guidelines referenced herein, constitute the entire agreement between you and SLTR Digital LLC regarding the Service and supersede all prior and contemporaneous agreements, proposals, representations, and understandings, whether written or oral.</p>
          <p>17.3. <strong>Severability.</strong> If any provision of these Terms is held by a court of competent jurisdiction or arbitrator to be invalid, illegal, or unenforceable, such provision shall be modified to the minimum extent necessary to make it enforceable, or if modification is not possible, severed from these Terms, and the remaining provisions shall continue in full force and effect.</p>
          <p>17.4. <strong>Waiver.</strong> Our failure to exercise or enforce any right or provision of these Terms shall not constitute a waiver of such right or provision. Any waiver must be in writing and signed by us to be effective.</p>
          <p>17.5. <strong>Assignment.</strong> You may not assign or transfer these Terms or any rights or obligations hereunder without our prior written consent. We may assign these Terms without restriction, including in connection with a merger, acquisition, reorganization, or sale of assets.</p>
          <p>17.6. <strong>Force Majeure.</strong> We shall not be liable for any failure or delay in performing our obligations under these Terms due to causes beyond our reasonable control, including but not limited to acts of God, natural disasters, pandemic, war, terrorism, riots, government actions, power failures, internet or telecommunications failures, or third-party service outages.</p>
          <p>17.7. <strong>Notices.</strong> We may send notices to you via the email address associated with your account or through the Service interface. You may send notices to us at support@luminetic.io. Notices are deemed received when sent via email (upon delivery confirmation) or when posted to the Service (upon posting).</p>
          <p>17.8. <strong>Headings.</strong> Section headings are for convenience of reference only and do not affect the interpretation of these Terms.</p>
          <p>17.9. <strong>No Third-Party Beneficiaries.</strong> These Terms are between you and SLTR Digital LLC. No third party has any rights or benefits under these Terms, except as expressly provided in the indemnification provisions.</p>
          <p>17.10. <strong>Export Compliance.</strong> You agree to comply with all applicable export and re-export control laws and regulations, including the Export Administration Regulations maintained by the U.S. Department of Commerce and sanctions programs administered by the U.S. Treasury Department&rsquo;s Office of Foreign Assets Control.</p>
          <p>17.11. <strong>Government Users.</strong> If you are a U.S. government end user, the Service is a &ldquo;Commercial Item&rdquo; as defined in 48 C.F.R. 2.101, and is licensed in accordance with these Terms.</p>
          <p>17.12. <strong>Electronic Agreement.</strong> By clicking &ldquo;I Agree&rdquo; or creating an account, you consent to entering into these Terms electronically and to receiving communications from us electronically. You agree that electronic agreements and communications have the same legal effect as physical, written documents.</p>

          <SectionTitle num="18">Contact Information</SectionTitle>
          <p>For questions, concerns, or notices regarding these Terms, contact:</p>
          <p><strong>SLTR Digital LLC</strong><br />Los Angeles, California<br />Email: support@luminetic.io</p>

          <SectionTitle num="19">Acknowledgment</SectionTitle>
          <p style={capsStyle}>BY CREATING AN ACCOUNT OR USING THE SERVICE, YOU ACKNOWLEDGE THAT:</p>
          <ul style={capsStyle}>
            <li>YOU HAVE READ AND UNDERSTOOD THESE TERMS IN THEIR ENTIRETY.</li>
            <li>YOU AGREE TO BE BOUND BY THESE TERMS.</li>
            <li>YOU UNDERSTAND THAT THE SERVICE PROVIDES AI-GENERATED ANALYSIS THAT IS ADVISORY IN NATURE AND DOES NOT GUARANTEE APP STORE APPROVAL.</li>
            <li>YOU UNDERSTAND THAT YOUR UPLOADED FILES ARE PERMANENTLY DELETED IMMEDIATELY UPON SCAN COMPLETION AND CANNOT BE RECOVERED.</li>
            <li>YOU UNDERSTAND THAT ALL CREDIT PURCHASES ARE FINAL AND NON-REFUNDABLE.</li>
            <li>YOU HAVE THE LEGAL RIGHT TO UPLOAD ANY FILES YOU SUBMIT FOR ANALYSIS.</li>
            <li>YOU ARE ENTERING INTO A LEGALLY BINDING AGREEMENT WITH SLTR DIGITAL LLC.</li>
          </ul>

          <div style={{
            marginTop: 48,
            paddingTop: 24,
            borderTop: '1px solid var(--border)',
          }}>
            <p style={{ fontStyle: 'italic', color: 'var(--text-dim)' }}>
              These Terms and Conditions are effective as of March 28, 2026.
            </p>
            <p style={{ fontStyle: 'italic', color: 'var(--text-dim)' }}>
              Copyright 2026 SLTR Digital LLC. All rights reserved.
            </p>
          </div>
        </article>
      </main>

      <Footer />
    </div>
  );
}

const capsStyle: React.CSSProperties = {
  fontSize: '0.82rem',
};

function SectionTitle({ num, children }: { num: string; children: React.ReactNode }) {
  return (
    <h2 style={{
      fontFamily: 'var(--display)',
      fontSize: '1.2rem',
      letterSpacing: 1.5,
      color: 'var(--text)',
      marginTop: 48,
      marginBottom: 16,
      paddingBottom: 10,
      borderBottom: '1px solid var(--border)',
    }}>
      {num}. {children}
    </h2>
  );
}
